# services:
#   - type: web
#     name: kishlay-rag-api
#     env: python
#     plan: free
#     buildCommand: "pip install -r requirements.txt"
#     startCommand: "uvicorn api_chatbot:app --host 0.0.0.0 --port $PORT"
#     runtime: "python3.10"

services:
  - type: web
    name: portfolio-chat
    env: python
    buildCommand: uv sync
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port 10000
